name: 'Build and release a Docker Image'
description: 'A reusable action to build and release Docker images with automatic version detection'
author: 'michielvha'
branding:
  icon: arrow-right-circle
  color: blue
inputs:
  version:
    description: 'GitVersion version to use'
    required: false
    default: 'dev'
  username:
    description: 'Docker Hub username'
    required: true
  password:
    description: 'Docker Hub password or token'
    required: true
  project:
    description: 'Docker image name (e.g., edgeforge/erm)'
    required: true
  platforms:
    description: 'Target platforms for Docker build'
    required: false
    default: 'linux/amd64'
  context:
    description: 'Docker build context'
    required: false
    default: '.'
  build-args:
    description: 'Additional build arguments to pass to Docker build (multiline string, e.g., "ARG1=value1\nARG2=value2"). IMAGE_NAME will be automatically set to the project name.'
    required: false
outputs:
  image-digest:
    description: 'Docker image digest'
    value: ${{ steps.build-push.outputs.digest }}
runs:
  using: 'composite'
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image
      id: build-push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        push: true
        tags: |
          ${{ inputs.username }}/${{ inputs.project }}:${{ inputs.version }}
          ${{ inputs.username }}/${{ inputs.project }}:latest
          ${{ inputs.username }}/${{ inputs.project }}:${{ github.sha }}
        platforms: ${{ inputs.platforms }}
        build-args: |
          IMAGE_NAME=${{ inputs.project }}
          ${{ inputs.build-args }}
    - name: Log out from Docker Hub
      shell: bash
      run: docker logout
