name: Example Usage of Docker Release Action

on:
  push:
    branches:
      - main
      - release/*
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch all history for GitVersion

      - name: Tag with GitVersion
        uses: michielvha/gitversion-tag-action@v5
        id: gitversion
        with:
          configFilePath: 'gitversion.yml'

      - name: Build and Push Docker Image
        id: docker-build
        uses: michielvha/docker-release-action@v1
        with:
          username: <your_username> # do not use a secret here, only variables will work. Secrets cannot be used here to create the docker upload path.
          password: ${{ secrets.DOCKER_PASSWORD }}
          project: 'my-app'
          version: ${{ steps.gitversion.outputs.semver }}
          platforms: 'linux/amd64,linux/arm64'
          context: '.'
      
      - name: Display outputs
        run: |
           echo "📦 Image digest: ${{ steps.docker-build.outputs.image-digest }}"
