name: Example Usage of Docker Release Action

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for GitVersion

      - name: Tag with GitVersion
        uses: michielvha/gitversion-tag-action@v3
        with:
          configFilePath: 'gitversion.yml'

      - name: Build and Push Docker Image
        id: docker-build
        uses: ./  # Use the local action for testing
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          project: 'erm'
          platforms: 'linux/amd64'
          context: '.'
      
      - name: Display outputs
        run: |
          echo "📦 Image digest: ${{ steps.build.outputs.image-digest }}"
